Mmf/schema based config for plugins
opennms-forge/distributed-scheduling-poc pull request #30
Opened 2022-08-02 22:39 UTC by mfrazier63

adds a simple schema communication back to the horizon server. 
Introduces a whiteboard that will send out a message about the plugin configs when the plugin is registered
Provides a simple reflection based scanner to extract plugin config schema information from custom annotations
Also adds a camel route behind a SEDA (memory) queue for collecting and aggregating all the plugin configs into a single message for the server.

2022-08-03 15:57 UTC, splatch requested changes
There are minor issues - I think main problem is propagation of field config metadata through grpc layer. I don't think we should be doing it. Field config metadata on server side is used to construct workflow (task) parameters. We send then only parameters, so worker or executor or minion should be validating what it receives with what it actually expects.

2022-08-03 15:57 UTC, splatch commented on ignite-worker/src/main/java/org/opennms/poc/ignite/worker/ignite/registries/OsgiServiceHolder.java
> +        detectorRegistry = new DetectorRegistryImpl(bundleContext, producerTemplate);
Maybe it would be a good idea to avoid direct dependency on camel in worker code through our own interface. `ProducerTemplate` is very rich in functionality, not sure if we want to promote its use.

2022-08-03 15:57 UTC, splatch commented on ignite-worker/src/main/java/org/opennms/poc/plugin/config/PluginConfigScanner.java
> +                    return fcm;
Just a styling suggestion - avoiding longer inline lambdas cleans up stack trace in case of failure. Maybe this `map` statement would be better with `this::mapConfigurationField)` or similar.

2022-08-03 15:57 UTC, splatch commented on model/src/main/java/org/opennms/poc/ignite/model/workflows/Workflow.java
> +    private List<FieldConfigMeta> fieldConfigMeta;
As suggested before - I don't think we need to send this back to worker. Worker should have access to `FieldConfigMetadata` based on its own runtime state.

2022-08-03 15:57 UTC, splatch commented on ignite-worker/src/main/java/org/opennms/poc/ignite/worker/workflows/impl/WorkflowExecutorLocalMonitorServiceImpl.java
> +            PluginConfigInjector.injectConfigs(foundMonitorManager, workflow.getFieldConfigMeta());
The `fieldConfigMeta` part should/may come from monitor manager.

2022-08-03 18:15 UTC, mfrazier63 commented on model/src/main/java/org/opennms/poc/ignite/model/workflows/Workflow.java
> +    private List<FieldConfigMeta> fieldConfigMeta;
Right, we have taken this as something that needs to be resolved later.

2022-08-03 18:16 UTC, mfrazier63 commented on ignite-worker/src/main/java/org/opennms/poc/ignite/worker/workflows/impl/WorkflowExecutorLocalMonitorServiceImpl.java
> +            PluginConfigInjector.injectConfigs(foundMonitorManager, workflow.getFieldConfigMeta());
It actually does, though the loop I diagramed earlier. WE just need to resolve the issue of how to transmit it back as mentioned in other comments/feedback.

2022-08-03 18:17 UTC, mfrazier63 commented on ignite-worker/src/main/java/org/opennms/poc/plugin/config/PluginConfigScanner.java
> +                    return fcm;
Will address in the move to horizon

2022-08-03 18:20 UTC, mfrazier63 commented on ignite-worker/src/main/java/org/opennms/poc/ignite/worker/ignite/registries/OsgiServiceHolder.java
> +        detectorRegistry = new DetectorRegistryImpl(bundleContext, producerTemplate);
Will address this in a future refactor when we "make it real"

2022-08-04 12:07 UTC, splatch approved these changes
I made some adjustments in blueprint which make it work end to end. Please check it out. Once it works for you its fine to push it into `main`.

2022-08-04 17:12 UTC, merged